destination: ../doc_developers-pdf
url: "http://127.0.0.1:4002"
baseurl: "/doc_developers"
port: 4002
print: true
print_title: Jekyll Documentation Theme for developers
print_subtitle: version 3.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true